import {Renderer} from './renderer.js';
const $=id=>document.getElementById(id);
import {effects,styles,defaults} from './effects.js';
const state={tool:'brush',previewQuality:'auto',wind:{direction:90,strength:.35},image:null,data:null,name:'Untitled map',layers:[],selected:null,playing:true,time:0,duration:12,mode:'paint',zoom:1,x:0,y:0,dirty:false,exporting:false,compare:false,space:false};
let placingOrigin=false,shapeStroke=null,polygon=null;
let renderer,toastTimer,stroke=null,panStart=null,jobId=null,cancelled=false,encoderReady=false;
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',5500);}
function selected(){return state.layers.find(l=>l.id===state.selected);}
function change(){state.dirty=true;}
const windEffects=[4,7,9,10,12,13];
function refreshWind(){const {direction,strength}=state.wind;const names=['North','NE','East','SE','South','SW','West','NW'];$('windDirection').value=direction;$('windStrength').value=Math.round(strength*100);$('windDirectionOut').textContent=names[Math.round(direction/45)%8]+' · '+direction+'°';$('windStrengthOut').textContent=strength===0?'Calm':Math.round(strength*100)+'%';$('windArrow').style.transform=`rotate(${direction-90}deg)`;}
$('windDirection').oninput=()=>{state.wind.direction=+$('windDirection').value;refreshWind();change();};
$('windStrength').oninput=()=>{state.wind.strength=+$('windStrength').value/100;refreshWind();change();};refreshWind();
function layerCanvas(){const c=document.createElement('canvas');const ratio=Math.min(1,2048/Math.max(state.image.width,state.image.height));c.width=Math.round(state.image.width*ratio);c.height=Math.round(state.image.height*ratio);return c;}
function makeLayer(type,variant=0){const effect=defaults(type,variant);return {...effect,id:crypto.randomUUID(),name:effect.name,visible:true,mask:layerCanvas(),revision:0,history:[]};}
function addLayer(type,variant=0){if(!state.image){toast('Open a map first, then add an effect.');return;}if(state.layers.length>=16){toast('This project supports up to 16 effect layers.');return;}const l=makeLayer(type,variant);if(type===7&&variant===1)l.name='Embers';state.layers.push(l);state.selected=l.id;change();refreshLayers();refreshInspector();toast(`${l.name} added. Paint on the map, or choose Fill map.`);}
const categories=[['Light & magic',[3,5,6,11,14,16]],['Water',[1,8,15]],['Atmosphere & weather',[2,4,9,12,13]],['Particles & foliage',[7,10]]];
for(const [name,types] of categories){const group=document.createElement('details');group.open=true;const heading=document.createElement('summary');heading.textContent=name;group.append(heading);const grid=document.createElement('div');grid.className='effectGrid';for(const effect of effects.filter(e=>types.includes(e.type))){const b=document.createElement('button');b.className='effectCard';b.innerHTML=`<span class="icon">${effect.icon}</span><span>${effect.name}</span>`;b.title=effect.hint;b.onclick=()=>addLayer(effect.type);grid.append(b);}if(types.includes(7)){const b=document.createElement('button');b.className='effectCard effectShortcut';b.innerHTML='<span class=icon>♨</span><span>Embers</span>';b.title='Warm rising embers. Paint above a brazier, campfire or lava.';b.onclick=()=>addLayer(7,1);grid.append(b);}group.append(grid);$('effects').append(group);}
function deleteLayer(id){const i=state.layers.findIndex(l=>l.id===id);if(i<0)return;state.layers.splice(i,1);if(state.selected===id)state.selected=state.layers[Math.min(i,state.layers.length-1)]?.id;change();refreshLayers();refreshInspector();}
// Storage and rendering are bottom-first; the list is top-first.
function dropLayer(id,targetId,above){if(id===targetId)return;const from=state.layers.findIndex(l=>l.id===id);if(from<0)return;const target=state.layers.find(l=>l.id===targetId);if(!target)return;const [layer]=state.layers.splice(from,1);state.layers.splice(state.layers.indexOf(target)+(above?1:0),0,layer);change();refreshLayers();}
function refreshLayers(){
 $('layerCount').textContent=state.layers.length;const box=$('layers');box.replaceChildren();
 if(!state.layers.length){const p=document.createElement('p');p.className='muted';p.textContent='Add an effect above to start painting.';box.append(p);}
 for(const l of [...state.layers].reverse()){
  const row=document.createElement('div');row.className='layer'+(l.id===state.selected?' selected':'');
  row.dataset.layerId=l.id;row.draggable=true;row.title='Drag to reorder; bottom layer is applied first';
  row.ondragstart=e=>{e.dataTransfer.setData('application/x-mapfx-layer',l.id);e.dataTransfer.effectAllowed='move';row.classList.add('dragging');};
  row.ondragover=e=>{if(!e.dataTransfer.types.includes('application/x-mapfx-layer'))return;e.preventDefault();row.classList.toggle('dropAbove',e.clientY<row.getBoundingClientRect().top+row.offsetHeight/2);row.classList.toggle('dropBelow',!row.classList.contains('dropAbove'));};
  row.ondragleave=()=>row.classList.remove('dropAbove','dropBelow');row.ondragend=()=>refreshLayers();
  row.ondrop=e=>{e.preventDefault();dropLayer(e.dataTransfer.getData('application/x-mapfx-layer'),l.id,e.clientY<row.getBoundingClientRect().top+row.offsetHeight/2);};
  const handle=document.createElement('span');handle.className='dragHandle';handle.textContent='⠿';handle.setAttribute('aria-hidden','true');
  const remove=document.createElement('button');remove.className='deleteLayer danger';remove.textContent='×';remove.title=`Delete ${l.name}`;remove.setAttribute('aria-label',remove.title);remove.onclick=()=>deleteLayer(l.id);
  const toggle=document.createElement('button');toggle.className='toggleLayer';toggle.textContent=l.visible?'◉':'○';toggle.title=l.visible?'Hide effect':'Show effect';toggle.setAttribute('aria-label',`${l.visible?'Hide':'Show'} ${l.name}`);toggle.onclick=()=>{l.visible=!l.visible;change();refreshLayers();};
  const name=document.createElement('button');name.className='selectLayer';name.textContent=l.name;name.onclick=()=>{state.selected=l.id;refreshLayers();refreshInspector();};row.append(handle,toggle,name,remove);box.append(row);
 }drawMask();
}
function parameter(label,key,min,max,step,format){const l=selected(),wrap=document.createElement('label'),out=document.createElement('output'),input=document.createElement('input');wrap.textContent=label;out.textContent=format(l[key]);input.type='range';input.min=min;input.max=max;input.step=step;input.value=l[key];input.setAttribute('aria-label',label);input.dataset.param=key;input.oninput=()=>{l[key]=+input.value;out.textContent=format(l[key]);change();};wrap.append(out,input);$('parameters').append(wrap);}
function refreshInspector(){cancelShape();placingOrigin=false;const l=selected();$('settings').hidden=!l;$('effectTitle').textContent=l?effects.find(e=>e.type===l.type).name:'A blank canvas';$('effectHint').textContent=l?l.hint:'Load your map and add an effect to start shaping the atmosphere.';
 if(l){$('layerName').value=l.name;$('color').value=l.color;$('color').parentElement.hidden=[2,8].includes(l.type);$('parameters').replaceChildren();parameter('Intensity','intensity',0,1,.01,v=>Math.round(v*100)+'%');parameter('Pattern size','scale',.25,4,.05,v=>v.toFixed(2)+'×');parameter('Loop speed','speed',1,5,1,v=>v+'×');if(styles[l.type]){const choices=styles[l.type];const label=document.createElement('label');label.textContent='Style';const select=document.createElement('select');select.setAttribute('aria-label','Style');choices.forEach((name,i)=>select.add(new Option(name,i)));select.value=l.variant;select.onchange=()=>{l.variant=+select.value;l.color=defaults(l.type,l.variant).color;applyLook('balanced');};label.append(select);$('parameters').prepend(label);}
 if([4,7,9,10,11,12,13,14,15].includes(l.type))parameter([4,12,13].includes(l.type)?'Coverage':l.type===11?'Ambient flash':'Density','density',0,1,.01,v=>Math.round(v*100)+'%');
 if(windEffects.includes(l.type)){const label=document.createElement('label');label.className='windToggle';const input=document.createElement('input');input.type='checkbox';input.checked=l.followWind;input.onchange=()=>{l.followWind=input.checked;change();refreshInspector();};label.append(input,document.createTextNode('Follow global wind'));$('parameters').append(label);}
 if((windEffects.includes(l.type)&&!l.followWind)||l.type===14)parameter('Direction','direction',0,360,1,v=>v+'°');
 if(l.type===9&&l.variant===0){parameter('Streak length','rainLength',0,1,.01,v=>Math.round(v*100)+'%');parameter('Rain splashes','splash',0,1,.01,v=>Math.round(v*100)+'%');}
 if([9,10].includes(l.type))parameter('Particle size','detail',0,1,.01,v=>Math.round(v*100)+'%');
 if(l.type===11)parameter('Flash duration','detail',0,1,.01,v=>Math.round(v*100)+'%');
 if(l.type===13)parameter('Edge softness','detail',0,1,.01,v=>Math.round(v*100)+'%');
 if(l.type===14)parameter('Beam softness','detail',0,1,.01,v=>Math.round(v*100)+'%');
 if(l.type===15)parameter('Ring size','detail',0,1,.01,v=>Math.round(v*100)+'%');
 if(l.type===16){parameter('Centre across','originX',0,1,.005,v=>Math.round(v*100)+'%');parameter('Centre down','originY',0,1,.005,v=>Math.round(v*100)+'%');const b=document.createElement('button');b.id='placeOrigin';b.className='wide';b.textContent='Place centre on map';b.onclick=()=>{placingOrigin=true;toast('Click the map to place the portal centre. Escape cancels.');};$('parameters').append(b);}
 if(l.type===3)parameter('Brightness threshold','detail',0,1,.01,v=>Math.round(v*100)+'%');if(l.type===7)parameter('Mote size','detail',0,1,.01,v=>Math.round(v*100)+'%');}drawMask();}
function applyLook(look){const l=selected();if(!l)return;const base=defaults(l.type,l.variant),factor={subtle:.55,balanced:1,dramatic:1.65}[look];for(const key of ['intensity','density','detail','rainLength','splash'])l[key]=base[key];l.intensity=Math.min(1,base.intensity*factor);l.density=Math.min(1,base.density*(look==='subtle'?.75:look==='dramatic'?1.35:1));change();refreshInspector();}
for(const look of ['subtle','balanced','dramatic'])$(look).onclick=()=>applyLook(look);
$('layerName').oninput=()=>{const l=selected();if(l){l.name=$('layerName').value;change();refreshLayers();}};
$('color').oninput=()=>{if(selected()){selected().color=$('color').value;change();}};
function snapshot(l){l.history.push({pixels:l.mask.getContext('2d').getImageData(0,0,l.mask.width,l.mask.height),originX:l.originX,originY:l.originY,scale:l.scale});if(l.history.length>10)l.history.shift();}
function maskChanged(l){l.revision++;change();drawMask();}
$('fill').onclick=()=>{const l=selected();if(!l)return;snapshot(l);const c=l.mask.getContext('2d');c.globalCompositeOperation='source-over';c.fillStyle='white';c.fillRect(0,0,l.mask.width,l.mask.height);maskChanged(l);};
$('clear').onclick=()=>{const l=selected();if(!l)return;snapshot(l);l.mask.getContext('2d').clearRect(0,0,l.mask.width,l.mask.height);maskChanged(l);};
$('undo').onclick=()=>{const l=selected();if(!l?.history.length)return;const old=l.history.pop();l.mask.getContext('2d').putImageData(old.pixels,0,0);for(const k of ['originX','originY','scale'])l[k]=old[k];maskChanged(l);refreshInspector();};
$('duplicate').onclick=()=>{const l=selected();if(!l||state.layers.length>=16)return;const copy=makeLayer(l.type);for(const k of ['intensity','scale','speed','detail','color','visible','density','direction','variant','followWind','rainLength','splash','originX','originY'])copy[k]=l[k];copy.name=l.name+' copy';copy.mask.getContext('2d').drawImage(l.mask,0,0);state.layers.push(copy);state.selected=copy.id;change();refreshLayers();refreshInspector();};
$('delete').onclick=()=>deleteLayer(state.selected);
function moveLayer(dir){const i=state.layers.findIndex(l=>l.id===state.selected),j=i+dir;if(i<0||j<0||j>=state.layers.length)return;[state.layers[i],state.layers[j]]=[state.layers[j],state.layers[i]];change();refreshLayers();}
$('up').onclick=()=>moveLayer(1);$('down').onclick=()=>moveLayer(-1);
function setMode(mode){cancelShape();state.mode=mode;for(const m of ['paint','erase','pan'])$(m).classList.toggle('active',m===mode);$('viewport').style.cursor=mode==='pan'?'grab':'crosshair';}
for(const mode of ['paint','erase','pan'])$(mode).onclick=()=>setMode(mode);
$('brushSize').oninput=()=>$('brushSizeOut').textContent=$('brushSize').value+' px';$('brushStrength').oninput=()=>$('brushStrengthOut').textContent=$('brushStrength').value+'%';
function drawMask(){const c=$('maskView'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);const l=selected();if(l&&$('showMask').checked&&!state.compare){ctx.drawImage(l.mask,0,0,c.width,c.height);ctx.globalCompositeOperation='source-in';ctx.fillStyle='#73dfc4';ctx.fillRect(0,0,c.width,c.height);ctx.globalCompositeOperation='source-over';}}
$('showMask').onchange=drawMask;
let previewTimer;
function previewDimensions(){const max=Math.max(state.image.width,state.image.height);const needed=state.previewQuality==='native'?max:state.previewQuality==='fast'?1600:Math.max(1600,max*state.zoom*(window.devicePixelRatio||1));const cap=[1600,2400,3200,max].filter(n=>n<=max).find(n=>n>=needed)||max;const ratio=Math.min(1,cap/max);return [Math.round(state.image.width*ratio),Math.round(state.image.height*ratio)];}
function updatePreviewDetail(){clearTimeout(previewTimer);if(!state.image||state.exporting)return;const [w,h]=previewDimensions();if(renderer.canvas.width===w&&renderer.canvas.height===h)return;const old=[renderer.canvas.width,renderer.canvas.height];try{renderer.setMap(state.image,w,h);}catch(e){try{renderer.setMap(state.image,...old);}catch{}toast('Full preview detail is unavailable: '+e.message);return;}$('maskView').width=w;$('maskView').height=h;drawMask();renderer.render(state.layers,state.time,state.duration,state.compare,state.wind);$('previewQuality').title=`Preview: ${w} × ${h}. Original: ${state.image.width} × ${state.image.height}. Export always uses original dimensions.`;}
$('previewQuality').onchange=()=>{state.previewQuality=$('previewQuality').value;updatePreviewDetail();};
$('actualSize').onclick=()=>{if(!state.image)return;const r=$('viewport').getBoundingClientRect();state.zoom=1;state.x=Math.round((r.width-state.image.width)/2);state.y=Math.round((r.height-state.image.height)/2);if(state.previewQuality==='fast'){state.previewQuality='auto';$('previewQuality').value='auto';}transform();updatePreviewDetail();};
function transform(){const s=$('stage');s.style.transform=`translate(${state.x}px,${state.y}px) scale(${state.zoom})`;$('zoomLabel').textContent=Math.round(state.zoom*100)+'%';clearTimeout(previewTimer);previewTimer=setTimeout(updatePreviewDetail,160);}
function fit(){if(!state.image)return;const r=$('viewport').getBoundingClientRect();state.zoom=Math.min((r.width-70)/state.image.width,(r.height-60)/state.image.height);state.x=(r.width-state.image.width*state.zoom)/2;state.y=(r.height-state.image.height*state.zoom)/2;transform();}
$('fit').onclick=fit;new ResizeObserver(()=>{if(state.image)fit();}).observe($('viewport'));
function point(e){const r=$('viewport').getBoundingClientRect();return {x:(e.clientX-r.left-state.x)/state.zoom,y:(e.clientY-r.top-state.y)/state.zoom};}
function stamp(p){const l=selected();if(!l)return;const ctx=l.mask.getContext('2d'),ratio=l.mask.width/state.image.width,r=+$('brushSize').value*.5*ratio,x=p.x*ratio,y=p.y*ratio;ctx.globalCompositeOperation=state.mode==='erase'?'destination-out':'source-over';const g=ctx.createRadialGradient(x,y,0,x,y,r);const a=+$('brushStrength').value/100;g.addColorStop(0,`rgba(255,255,255,${a})`);g.addColorStop(.45,`rgba(255,255,255,${a*.8})`);g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.globalCompositeOperation='source-over';l.revision++;}
const view=$('viewport');
function cancelShape(){polygon=null;$('polygonOutline').hidden=true;shapeStroke=null;$('shapeOutline').hidden=true;}
$('shapeTool').onchange=()=>{$('shapeSoftness').disabled=$('shapeTool').value==='polygon';cancelShape();state.tool=$('shapeTool').value;if(state.mode==='pan')setMode('paint');};
function drawPolygon(next){const o=$('polygonOutline');o.hidden=false;o.setAttribute('width',state.image.width);o.setAttribute('height',state.image.height);const pts=[...polygon.points,...(next?[next]:[])];o.querySelector('polyline').setAttribute('points',pts.map(p=>p.x+','+p.y).join(' '));const group=o.querySelector('g');group.replaceChildren();polygon.points.forEach((p,i)=>{const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',p.x);dot.setAttribute('cy',p.y);dot.setAttribute('r',(i===0?6:3)/state.zoom);group.append(dot);});}
function finishPolygon(){if(!polygon||polygon.points.length<3)return;const drag=polygon,l=state.layers.find(l=>l.id===drag.id);cancelShape();if(!l)return;snapshot(l);const c=document.createElement('canvas');c.width=l.mask.width;c.height=l.mask.height;const ctx=c.getContext('2d');ctx.scale(c.width/state.image.width,c.height/state.image.height);ctx.beginPath();drag.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle='white';ctx.fill('evenodd');const dest=l.mask.getContext('2d');dest.save();dest.globalAlpha=+$('brushStrength').value/100;dest.globalCompositeOperation=drag.erase?'destination-out':'source-over';dest.drawImage(c,0,0);dest.restore();maskChanged(l);}
function shapeBounds(e){const p=point(e),a=shapeStroke.start;let dx=p.x-a.x,dy=p.y-a.y;if(e.shiftKey){const size=Math.max(Math.abs(dx),Math.abs(dy));dx=Math.sign(dx||1)*size;dy=Math.sign(dy||1)*size;}return {x:Math.min(a.x,a.x+dx),y:Math.min(a.y,a.y+dy),w:Math.abs(dx),h:Math.abs(dy)};}
function previewShape(e){const b=shapeBounds(e);shapeStroke.bounds=b;const o=$('shapeOutline');o.hidden=false;o.style.cssText=`left:${b.x}px;top:${b.y}px;width:${b.w}px;height:${b.h}px;border-radius:${state.tool==='ellipse'?'50%':'0'};`;}
function finishShape(e){if(!shapeStroke)return;const drag=shapeStroke,l=state.layers.find(l=>l.id===drag.id);const b=shapeBounds(e);cancelShape();if(!l||b.w*state.zoom<3||b.h*state.zoom<3)return;
 snapshot(l);const c=document.createElement('canvas');c.width=l.mask.width;c.height=l.mask.height;const ctx=c.getContext('2d'),rx=c.width/state.image.width,ry=c.height/state.image.height;const feather=+$('shapeSoftness').value/100;
 // Concentric filled contours feather inward, keeping the dragged bounds exact.
 const steps=feather?32:1;ctx.fillStyle='white';for(let i=0;i<steps;i++){const inset=feather*(1-(i+1)/steps)*.5;ctx.globalAlpha=1/(steps-i);const x=(b.x+b.w*inset)*rx,y=(b.y+b.h*inset)*ry,w=b.w*(1-2*inset)*rx,h=b.h*(1-2*inset)*ry;ctx.beginPath();if(state.tool==='ellipse')ctx.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2);else ctx.rect(x,y,w,h);ctx.fill();}
 const dest=l.mask.getContext('2d');dest.save();dest.globalAlpha=+$('brushStrength').value/100;dest.globalCompositeOperation=drag.erase?'destination-out':'source-over';dest.drawImage(c,0,0);dest.restore();
 if(l.type===16&&state.tool==='ellipse'&&!drag.erase){l.originX=Math.max(0,Math.min(1,(b.x+b.w/2)/state.image.width));l.originY=Math.max(0,Math.min(1,(b.y+b.h/2)/state.image.height));l.scale=Math.max(.25,Math.min(4,Math.min(b.w,b.h)/(420*1.18)));}
 maskChanged(l);refreshInspector();}

view.onpointerdown=e=>{if(!state.image||state.exporting||e.button>1)return;if(placingOrigin){const l=selected();if(l?.type===16){const p=point(e);l.originX=Math.max(0,Math.min(1,p.x/state.image.width));l.originY=Math.max(0,Math.min(1,p.y/state.image.height));change();refreshInspector();}placingOrigin=false;return;}view.setPointerCapture(e.pointerId);if(state.mode==='pan'||state.space||e.button===1){panStart={x:e.clientX,y:e.clientY,ox:state.x,oy:state.y};return;}if(!selected()){toast('Choose an effect on the left before painting.');return;}if(state.tool==='polygon'){const p=point(e);if(!polygon)polygon={id:selected().id,erase:state.mode==='erase',points:[]};const first=polygon.points[0];if(first&&polygon.points.length>=3&&Math.hypot(p.x-first.x,p.y-first.y)*state.zoom<10){finishPolygon();return;}polygon.points.push(p);drawPolygon();return;}if(state.tool!=='brush'){shapeStroke={id:selected().id,start:point(e),erase:state.mode==='erase'};previewShape(e);return;}snapshot(selected());stroke=point(e);stamp(stroke);maskChanged(selected());};
view.onpointermove=e=>{const r=view.getBoundingClientRect(),cursor=$('brushCursor'),size=+$('brushSize').value*state.zoom;cursor.style.cssText=`display:${state.image&&state.tool==='brush'&&state.mode!=='pan'&&!state.space?'block':'none'};left:${e.clientX-r.left}px;top:${e.clientY-r.top}px;width:${size}px;height:${size}px;`;if(panStart){state.x=panStart.ox+e.clientX-panStart.x;state.y=panStart.oy+e.clientY-panStart.y;transform();}else if(polygon){drawPolygon(point(e));}else if(shapeStroke){previewShape(e);}else if(stroke){const next=point(e),dist=Math.hypot(next.x-stroke.x,next.y-stroke.y),steps=Math.max(1,Math.ceil(dist/(+$('brushSize').value*.18)));for(let i=1;i<=steps;i++)stamp({x:stroke.x+(next.x-stroke.x)*i/steps,y:stroke.y+(next.y-stroke.y)*i/steps});stroke=next;maskChanged(selected());}};
view.onpointerup=e=>{finishShape(e);stroke=null;panStart=null;};view.onpointercancel=()=>{cancelShape();stroke=null;panStart=null;};view.onpointerleave=()=>$('brushCursor').style.display='none';
view.onwheel=e=>{if(!state.image)return;e.preventDefault();const r=view.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,old=state.zoom;state.zoom=Math.max(.03,Math.min(4,state.zoom*Math.exp(-e.deltaY*.001)));state.x=mx-(mx-state.x)*state.zoom/old;state.y=my-(my-state.y)*state.zoom/old;transform();};
document.onkeydown=e=>{if(e.key==='Escape'){placingOrigin=false;cancelShape();}if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)||state.exporting||$('exportDialog').open||$('helpDialog').open)return;if(polygon&&['Enter','Backspace','Delete'].includes(e.key)){e.preventDefault();if(e.key==='Enter')finishPolygon();else{polygon.points.pop();if(!polygon.points.length)cancelShape();else drawPolygon();}return;}if(e.code==='Space'){e.preventDefault();state.space=true;}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();}if(e.key.toLowerCase()==='b')setMode('paint');if(e.key.toLowerCase()==='e')setMode('erase');if(e.key.toLowerCase()==='h')setMode('pan');};document.onkeyup=e=>{if(e.code==='Space')state.space=false;};window.onblur=()=>{cancelShape();state.space=false;state.compare=false;stroke=null;panStart=null;};
$('play').onclick=()=>{state.playing=!state.playing;$('play').textContent=state.playing?'❚❚':'▶';};$('scrub').oninput=()=>{state.time=+$('scrub').value;state.playing=false;$('play').textContent='▶';};
$('compare').onpointerdown=e=>{e.target.setPointerCapture(e.pointerId);state.compare=true;drawMask();};$('compare').onpointerup=$('compare').onpointercancel=()=>{state.compare=false;drawMask();};
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
function imageFrom(data){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('The image could not be opened.'));image.src=data;});}
async function loadMap(data,name){cancelShape();
 const image=await imageFrom(data);if(image.width*image.height>100000000)throw Error('This image exceeds the 100 megapixel editor limit. It has not been resized.');
 const ratio=Math.min(1,1600/Math.max(image.width,image.height));renderer.setMap(image,Math.round(image.width*ratio),Math.round(image.height*ratio));
 placingOrigin=false;state.wind={direction:90,strength:.35};refreshWind();state.image=image;state.data=data;state.name=name;state.layers=[];state.selected=null;state.time=0;state.dirty=false;
 $('mapName').textContent=name;$('mapInfo').textContent=`${image.width} × ${image.height} pixels`;
 $('stage').style.width=image.width+'px';$('stage').style.height=image.height+'px';$('stage').style.display='block';$('maskView').width=renderer.canvas.width;$('maskView').height=renderer.canvas.height;$('welcome').hidden=true;$('save').disabled=false;$('export').disabled=!encoderReady;fit();refreshLayers();refreshInspector();
}
function mayReplace(){return !state.dirty||confirm('Open a different map? Save your project first if you want to keep the current edits.');}
$('load').onclick=$('welcomeOpen').onclick=()=>$('mapFile').click();$('openProject').onclick=()=>$('projectFile').click();
$('mapFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||!mayReplace())return;try{await loadMap(await fileData(file),file.name.replace(/\.[^.]+$/,''));}catch(e){toast(e.message);}};
view.ondragover=e=>{e.preventDefault();};view.ondrop=async e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(!file||!mayReplace())return;try{if(file.name.endsWith('.mapfx'))await openProject(await file.text());else await loadMap(await fileData(file),file.name.replace(/\.[^.]+$/,''));}catch(e){toast(e.message);}};
function downloadBlob(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function projectData(){return {format:'map-fx-studio',version:1,name:state.name,image:state.data,width:state.image.width,height:state.image.height,duration:state.duration,wind:{...state.wind},layers:state.layers.map(l=>({type:l.type,name:l.name,visible:l.visible,intensity:l.intensity,scale:l.scale,speed:l.speed,detail:l.detail,color:l.color,density:l.density,direction:l.direction,variant:l.variant,followWind:l.followWind,rainLength:l.rainLength,splash:l.splash,originX:l.originX,originY:l.originY,mask:l.mask.toDataURL()}))};}
$('save').onclick=()=>{if(!state.image)return;downloadBlob(new Blob([JSON.stringify(projectData())],{type:'application/json'}),state.name+'.mapfx');state.dirty=false;toast('Editable project saved with your map and painted effect areas.');};
async function openProject(text){const data=JSON.parse(text);if(data.format!=='map-fx-studio'||data.version!==1||!Array.isArray(data.layers)||data.layers.length>16||!/^data:image\/(png|jpeg|webp);base64,/.test(data.image))throw Error('This is not a supported Mapmancer project.');
 // Validate the whole project before replacing the current work.
 if(data.wind!==undefined&&(!data.wind||!Number.isFinite(data.wind.direction)||!Number.isFinite(data.wind.strength)))throw Error('Invalid global wind settings.');
 const masks=[];for(const item of data.layers){if(!effects.some(e=>e.type===item.type)||!/^#[a-f0-9]{6}$/i.test(item.color)||!/^data:image\/png;base64,/.test(item.mask))throw Error('This project has an invalid effect layer.');for(const key of ['intensity','scale','speed','detail'])if(!Number.isFinite(item[key]))throw Error('Invalid effect setting.');for(const key of ['density','direction','variant','rainLength','splash','originX','originY'])if(item[key]!==undefined&&!Number.isFinite(item[key]))throw Error('Invalid effect setting.');if(item.followWind!==undefined&&typeof item.followWind!=='boolean')throw Error('Invalid wind setting.');masks.push(await imageFrom(item.mask));}
 await loadMap(data.image,String(data.name||'Untitled map'));state.wind=data.wind?{direction:((Math.round(data.wind.direction)%360)+360)%360,strength:Math.max(0,Math.min(1,data.wind.strength))}:{direction:90,strength:0};refreshWind();state.duration=[6,10,12,15,20].includes(data.duration)?data.duration:12;$('duration').value=state.duration;updateDuration();
 for(let i=0;i<data.layers.length;i++){const item=data.layers[i],l=makeLayer(item.type);l.name=String(item.name).slice(0,60);l.visible=!!item.visible;l.intensity=Math.max(0,Math.min(1,item.intensity));l.scale=Math.max(.25,Math.min(4,item.scale));l.speed=Math.max(1,Math.min(5,Math.round(item.speed)));l.detail=Math.max(0,Math.min(1,item.detail));l.originX=Math.max(0,Math.min(1,item.originX??.5));l.originY=Math.max(0,Math.min(1,item.originY??.5));l.followWind=item.followWind??false;l.rainLength=Math.max(0,Math.min(1,item.rainLength??.55));l.splash=Math.max(0,Math.min(1,item.splash??.25));l.color=item.color;l.density=Math.max(0,Math.min(1,item.density??l.density));l.direction=Math.max(0,Math.min(360,item.direction??l.direction));l.variant=Math.max(0,Math.min((styles[l.type]?.length??1)-1,Math.round(item.variant??0)));l.mask.getContext('2d').drawImage(masks[i],0,0,l.mask.width,l.mask.height);state.layers.push(l);}
 state.selected=state.layers.at(-1)?.id;state.dirty=false;refreshLayers();refreshInspector();toast('Project restored. Your effect layers are ready to edit.');
}
$('projectFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||!mayReplace())return;try{await openProject(await file.text());}catch(e){toast(e.message);}};
$('demo').onclick=async()=>{if(!mayReplace())return;try{const r=await fetch('/api/example/'+$('exampleChoice').value);if(!r.ok)throw Error('This example is unavailable.');await openProject(await r.text());toast('Example loaded. Toggle layers, change styles, or paint your own effects.');}catch(e){toast(e.message);}};
function updateDuration(){state.duration=+$('duration').value;$('scrub').max=state.duration;$('durationLabel').textContent=state.duration+'s loop';state.time%=state.duration;}
$('duration').onchange=()=>{updateDuration();change();};
$('export').onclick=()=>{$('exportDimensions').textContent=`${state.image.width} × ${state.image.height} pixels · Exact original dimensions`;$('exportName').value=state.name;$('exportDialog').showModal();};
async function api(path,data){const response=await fetch(path,{method:'POST',headers:{'X-Map-FX':'studio','Content-Type':data instanceof Blob?'image/png':'application/json'},body:data instanceof Blob?data:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Export failed');return result;}
function png(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('Could not capture the full-size frame.')),'image/png'));}
async function exportMap(){
 if(state.exporting)return;state.exporting=true;cancelled=false;jobId=null;let full;
 $('startExport').disabled=true;$('progressArea').hidden=false;$('exportResult').hidden=true;$('progress').value=0;$('progressText').textContent='Preparing the original-size canvas…';$('cancelExport').disabled=false;
 for(const id of ['duration','fps','quality','exportName'])$(id).disabled=true;
 try{
  const canvas=document.createElement('canvas');full=new Renderer(canvas);full.setMap(state.image,state.image.width,state.image.height);
  const fps=+$('fps').value,frames=state.duration*fps,exportWind={...state.wind};
  const result=await api('/api/export/start',{name:$('exportName').value,width:state.image.width,height:state.image.height,fps,frames,quality:$('quality').value});jobId=result.id;
  const begin=performance.now();
  for(let i=0;i<frames;i++){
   if(cancelled)throw Error('Export cancelled.');
   full.render(state.layers,i/fps,state.duration,false,exportWind);await api(`/api/export/${jobId}/frame`,await png(canvas));
   $('progress').value=(i+1)/frames*95;const elapsed=(performance.now()-begin)/1000,remaining=elapsed/(i+1)*(frames-i-1);
   $('progressText').textContent=`Rendering frame ${i+1} of ${frames} · ${remaining>60?Math.ceil(remaining/60)+' min':Math.ceil(remaining)+' sec'} estimated remaining`;
   await new Promise(resolve=>setTimeout(resolve,0));
  }
  $('progressText').textContent='Finishing the WebM encoding…';const done=await api(`/api/export/${jobId}/finish`,{});if(cancelled||done.cancelled)throw Error('Export cancelled.');$('progress').value=100;$('progressText').textContent=`Complete · ${(done.size/1048576).toFixed(1)} MiB · ${state.image.width} × ${state.image.height} pixels`;
  $('exportResult').hidden=false;$('download').href=done.url;$('download').download=$('exportName').value+'.webm';$('exportPath').textContent='Also saved on this computer: '+done.path;$('cancelExport').disabled=true;toast('Your WebM is ready. Original map dimensions preserved.');jobId=null;
 }catch(e){if(jobId){try{await api(`/api/export/${jobId}/cancel`,{});}catch{}}$('progressText').textContent=e.message;toast(e.message);}finally{full?.dispose();state.exporting=false;jobId=null;$('startExport').disabled=false;for(const id of ['duration','fps','quality','exportName'])$(id).disabled=false;}
}
$('startExport').onclick=exportMap;$('cancelExport').onclick=async()=>{cancelled=true;$('cancelExport').disabled=true;$('progressText').textContent='Cancelling…';if(jobId)try{await api(`/api/export/${jobId}/cancel`,{});}catch{}};
$('exportDialog').addEventListener('cancel',e=>{if(state.exporting)e.preventDefault();});$('exportDialog').querySelector('form').onsubmit=e=>{if(state.exporting)e.preventDefault();};
$('help').onclick=()=>$('helpDialog').showModal();window.addEventListener('beforeunload',e=>{if(state.dirty||state.exporting){e.preventDefault();e.returnValue='';}});
let previous=performance.now(),lastDraw=0;
function tick(now){requestAnimationFrame(tick);const delta=Math.min((now-previous)/1000,.1);previous=now;if(state.playing&&!state.exporting)state.time=(state.time+delta)%state.duration;if(now-lastDraw<40||!state.image||state.exporting)return;lastDraw=now;try{renderer.render(state.layers,state.time,state.duration,state.compare,state.wind);}catch(e){toast(e.message);state.playing=false;return;}$('time').textContent=state.time.toFixed(1)+'s';$('scrub').value=state.time;}
try{renderer=new Renderer($('preview'));requestAnimationFrame(tick);}catch(e){toast(e.message);$('welcomeOpen').disabled=true;}
fetch('/api/status').then(r=>r.json()).then(s=>{encoderReady=s.encoder;if(!s.encoder)toast('Preview is ready, but FFmpeg is missing. See the setup guide to enable WebM export.');}).catch(()=>toast('The local server is unavailable. Reopen the program launcher.'));
// A small inspection surface for local automated checks; no private file access.
window.mapFX={effects,styles,state,loadMap,openProject,projectData,addLayer,renderer,exportMap,renderAt:t=>renderer.render(state.layers,t,state.duration,false,state.wind)};

const systemTheme=matchMedia('(prefers-color-scheme: light)');
function applyTheme(){const choice=$('theme').value;document.documentElement.dataset.theme=choice==='system'?(systemTheme.matches?'light':'dark'):choice;}
try{$('theme').value=localStorage.getItem('mapmancer-theme')||'system';}catch{}if(!['light','dark','system'].includes($('theme').value))$('theme').value='system';
$('theme').onchange=()=>{try{localStorage.setItem('mapmancer-theme',$('theme').value);}catch{}applyTheme();};systemTheme.addEventListener('change',applyTheme);applyTheme();
